[build-system]
requires = ["setuptools >= 77.0.3"]
build-backend = "setuptools.build_meta"

[project]
name = "pizero-bikecomputer-v2"
version = "0.1.0"
description = ""
readme = "README.md"
requires-python = ">= 3.12, <=3.13"
dependencies = [
  "aiohttp==3.10.10",
  "aiofiles==24.1.0",
  "crdp",
  "numpy==1.26.4",
  "oyaml==1.0",
  "pillow==11.0.0",
  "pyqt6==6.10.0",
  "pyqtgraph==0.13.7",
  "qasync==0.28.0",
  "timezonefinder==6.5.4"
]

[project.optional-dependencies]
dbus = [
    "dbus-next==0.2.3"
]
gadgetbridge = [
    "bluez-peripheral==0.1.7"
]
polyline = [
    "polyline==2.0.0"
]

[dependency-groups]
dev = [
  "pre-commit >= 4.0.1"
]

[tool.uv.extra-build-dependencies]
crdp = ["Cython"]

[[tool.uv.index]]
name = "crdp"
url = "https://github.com/hishizuka/crdp.git"
